#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
CHAGEE (CHA) Initiation Report — Word (.docx) Generator
Generated by 05-writer (v0.1) — 2026-08-08

基于 04-analyst/analysis.md + 02-cleaner/cleaned.md
BitGates 投行风格: Calibri (latin) + SimSun (eastAsia), 黑/红/灰
"""
from docx import Document
from docx.shared import Pt, Inches, RGBColor, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH, WD_LINE_SPACING
from docx.enum.table import WD_ALIGN_VERTICAL, WD_TABLE_ALIGNMENT
from docx.oxml.ns import qn
from lxml import etree
from datetime import datetime

# === BitGates 投行设计系统 ===
COLOR_BLACK = RGBColor(0x2b, 0x2d, 0x42)    # 主色 - 深蓝黑
COLOR_RED = RGBColor(0xd9, 0x04, 0x29)      # 强调 - 投行红
COLOR_GRAY = RGBColor(0x8d, 0x99, 0xae)     # 副色 - 灰
COLOR_BG = RGBColor(0xed, 0xf2, 0xf7)       # 背景 - 浅蓝
COLOR_GREEN = RGBColor(0x06, 0xa7, 0x7c)    # 正向 - 绿
COLOR_AMBER = RGBColor(0xe6, 0xa2, 0x3a)    # 警示 - 琥珀
FONT_LATIN = "Calibri"
FONT_EA = "SimSun"


def set_font(run, latin=FONT_LATIN, eastasia=FONT_EA, size=10.5, bold=False, color=COLOR_BLACK):
    """Set font with cross-platform safe latin + eastAsia."""
    run.font.name = latin
    run.font.size = Pt(size)
    run.font.bold = bold
    run.font.color.rgb = color
    rPr = run._r.get_or_add_rPr()
    for tag in ['ea', 'cs']:
        existing = rPr.find(qn(f'a:{tag}'))
        if existing is not None:
            rPr.remove(existing)
        el = etree.SubElement(rPr, qn(f'a:{tag}'))
        el.set('typeface', eastasia)


def add_paragraph(doc, text, size=10.5, bold=False, color=COLOR_BLACK,
                  align=WD_ALIGN_PARAGRAPH.LEFT, space_after=6, indent=None):
    p = doc.add_paragraph()
    p.alignment = align
    p.paragraph_format.space_after = Pt(space_after)
    p.paragraph_format.line_spacing = 1.3
    if indent:
        p.paragraph_format.left_indent = Cm(indent)
    run = p.add_run(text)
    set_font(run, size=size, bold=bold, color=color)
    return p


def add_heading(doc, text, level=1, color=COLOR_RED):
    """Headings: H1 = 18pt red, H2 = 14pt black, H3 = 12pt black bold."""
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.LEFT
    p.paragraph_format.space_before = Pt(12)
    p.paragraph_format.space_after = Pt(6)
    if level == 1:
        size, bold = 18, True
    elif level == 2:
        size, bold = 14, True
    else:
        size, bold = 12, True
    run = p.add_run(text)
    set_font(run, size=size, bold=bold, color=color)
    return p


def add_horizontal_line(doc, color="D90429", size=12):
    """Add a red horizontal divider line."""
    p = doc.add_paragraph()
    pPr = p._p.get_or_add_pPr()
    pBdr = etree.SubElement(pPr, qn('w:pBdr'))
    bottom = etree.SubElement(pBdr, qn('w:bottom'))
    bottom.set(qn('w:val'), 'single')
    bottom.set(qn('w:sz'), str(size))
    bottom.set(qn('w:space'), '1')
    bottom.set(qn('w:color'), color)


def add_bullet(doc, text, indent=0.5, color=COLOR_BLACK, size=10.5):
    p = doc.add_paragraph(style='List Bullet')
    p.paragraph_format.left_indent = Cm(indent)
    p.paragraph_format.space_after = Pt(3)
    run = p.add_run(text)
    set_font(run, size=size, color=color)
    return p


def add_kpi_card_table(doc, kpis):
    """Add a 4-column KPI card row (BitGates style)."""
    table = doc.add_table(rows=2, cols=len(kpis))
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    # Row 1: red color band
    for i, (val, _) in enumerate(kpis):
        cell = table.rows[0].cells[i]
        cell.text = ""
        para = cell.paragraphs[0]
        para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = para.add_run(val)
        set_font(run, size=18, bold=True, color=COLOR_RED)
        # bg color
        tcPr = cell._tc.get_or_add_tcPr()
        shd = etree.SubElement(tcPr, qn('w:shd'))
        shd.set(qn('w:fill'), 'EDF2F7')
    # Row 2: label
    for i, (_, label) in enumerate(kpis):
        cell = table.rows[1].cells[i]
        cell.text = ""
        para = cell.paragraphs[0]
        para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = para.add_run(label)
        set_font(run, size=9, bold=False, color=COLOR_GRAY)
    doc.add_paragraph()  # spacer


def add_data_table(doc, headers, rows, col_widths=None, header_color=COLOR_RED):
    """Add a styled data table with red header."""
    table = doc.add_table(rows=1 + len(rows), cols=len(headers))
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    # Header
    for i, h in enumerate(headers):
        cell = table.rows[0].cells[i]
        cell.text = ""
        para = cell.paragraphs[0]
        para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = para.add_run(h)
        set_font(run, size=10, bold=True, color=RGBColor(0xFF, 0xFF, 0xFF))
        tcPr = cell._tc.get_or_add_tcPr()
        shd = etree.SubElement(tcPr, qn('w:shd'))
        shd.set(qn('w:fill'), 'D90429')
    # Body
    for r_idx, row in enumerate(rows):
        for c_idx, val in enumerate(row):
            cell = table.rows[r_idx + 1].cells[c_idx]
            cell.text = ""
            para = cell.paragraphs[0]
            para.alignment = WD_ALIGN_PARAGRAPH.CENTER
            run = para.add_run(str(val))
            # 第一列左对齐, 加粗
            if c_idx == 0:
                para.alignment = WD_ALIGN_PARAGRAPH.LEFT
                set_font(run, size=9.5, bold=True, color=COLOR_BLACK)
            else:
                set_font(run, size=9.5, bold=False, color=COLOR_BLACK)
            # 隔行底色
            if r_idx % 2 == 1:
                tcPr = cell._tc.get_or_add_tcPr()
                shd = etree.SubElement(tcPr, qn('w:shd'))
                shd.set(qn('w:fill'), 'F7F8FA')
    if col_widths:
        for i, w in enumerate(col_widths):
            for row in table.rows:
                row.cells[i].width = Cm(w)
    doc.add_paragraph()


def add_callout(doc, label, text, color=COLOR_RED):
    """Add a BitGates-style callout (e.g., INVESTMENT THESIS)."""
    p = doc.add_paragraph()
    p.paragraph_format.space_before = Pt(6)
    p.paragraph_format.space_after = Pt(6)
    p.paragraph_format.left_indent = Cm(0.3)
    p.paragraph_format.right_indent = Cm(0.3)
    # bg color
    pPr = p._p.get_or_add_pPr()
    shd = etree.SubElement(pPr, qn('w:shd'))
    shd.set(qn('w:fill'), 'EDF2F7')
    # label
    r1 = p.add_run(f"  {label}  ")
    set_font(r1, size=9.5, bold=True, color=RGBColor(0xFF, 0xFF, 0xFF))
    # colored badge via shading on run (approximation)
    rPr = r1._r.get_or_add_rPr()
    shd2 = etree.SubElement(rPr, qn('w:shd'))
    shd2.set(qn('w:fill'), 'D90429' if color == COLOR_RED else '2B2D42')
    # text
    r2 = p.add_run(f"  {text}")
    set_font(r2, size=10, color=COLOR_BLACK)
    return p


# === Build Report ===
doc = Document()

# Page setup
for section in doc.sections:
    section.top_margin = Cm(2.0)
    section.bottom_margin = Cm(2.0)
    section.left_margin = Cm(2.0)
    section.right_margin = Cm(2.0)

# === Page 1: Cover ===
# Title bar
p = doc.add_paragraph()
p.alignment = WD_ALIGN_PARAGRAPH.LEFT
p.paragraph_format.space_after = Pt(2)
r = p.add_run("守仁资产研究 / Shouren Research")
set_font(r, size=10, bold=True, color=COLOR_GRAY)

# Logo-like header bar
p = doc.add_paragraph()
p.paragraph_format.space_before = Pt(20)
p.paragraph_format.space_after = Pt(4)
pPr = p._p.get_or_add_pPr()
shd = etree.SubElement(pPr, qn('w:shd'))
shd.set(qn('w:fill'), 'D90429')
r = p.add_run("  INITIATION OF COVERAGE  |  首次覆盖  ")
set_font(r, size=11, bold=True, color=RGBColor(0xFF, 0xFF, 0xFF))

# Title
add_paragraph(doc, "CHAGEE (CHA)", size=36, bold=True, color=COLOR_BLACK, space_after=4)
add_paragraph(doc, "霸王茶姬 (NASDAQ: CHA)", size=20, bold=False, color=COLOR_RED, space_after=2)
add_paragraph(doc, "转型阵痛期的估值再校准", size=18, bold=True, color=COLOR_BLACK, space_after=18)

# Rating callout
p = doc.add_paragraph()
p.alignment = WD_ALIGN_PARAGRAPH.LEFT
p.paragraph_format.space_after = Pt(6)
r1 = p.add_run("  评级  ")
set_font(r1, size=14, bold=True, color=RGBColor(0xFF, 0xFF, 0xFF))
rPr = r1._r.get_or_add_rPr()
shd = etree.SubElement(rPr, qn('w:shd'))
shd.set(qn('w:fill'), 'D90429')

r2 = p.add_run("  HOLD (中性)   |   ")
set_font(r2, size=16, bold=True, color=COLOR_BLACK)

r3 = p.add_run("目标价 US$9.55   |   ")
set_font(r3, size=14, bold=True, color=COLOR_BLACK)

r4 = p.add_run("现价 US$11.19   |   ")
set_font(r4, size=14, color=COLOR_BLACK)

r5 = p.add_run("隐含 -14.7%")
set_font(r5, size=14, bold=True, color=COLOR_RED)

# Method
p = doc.add_paragraph()
p.paragraph_format.space_before = Pt(8)
p.paragraph_format.space_after = Pt(2)
r = p.add_run("估值方法: PE + Forward PE + 横向 Peer Comparables (同业可比)")
set_font(r, size=10.5, color=COLOR_GRAY)

# Coverage info
p = doc.add_paragraph()
r = p.add_run(f"覆盖日期: 2026-08-08  |  数据截止: 2026-07-31  |  分析师: 守仁研究  |  报告类型: Initiation (深)")
set_font(r, size=9, color=COLOR_GRAY)

# Spacer
doc.add_paragraph()
doc.add_paragraph()

# KPI cards
add_kpi_card_table(doc, [
    ("US$2.14B", "当前市值"),
    ("17.0x", "Forward PE 2026E"),
    ("+15.6%", "vs 同业 median (14.7x)"),
    ("HOLD", "评级")
])

# Disclaimer
add_paragraph(doc, "本报告基于公开信息 (SEC EDGAR + 同业财报 + 公开新闻) 整理, 不构成投资建议。投资者应独立判断并承担风险。",
              size=8, color=COLOR_GRAY, space_after=4)

doc.add_page_break()

# === Page 2: Investment Thesis ===
add_heading(doc, "一、投资要点 (Investment Thesis)", level=1)
add_horizontal_line(doc)

# 4 thesis cards
add_callout(doc, "THESIS 1",
            "营收断崖 + 利润腰斩: FY2024 净利 ¥2.52B → FY2025 ¥1.17B (-53%); 营收增速从 +167% 跌到 +4%; Q1 2026 净利再 -34% YoY",
            COLOR_RED)

add_callout(doc, "THESIS 2",
            "加盟萎缩信号: Q4 2025 起连续 2 季度加盟门店净关 (-230 家), 同期自营 +308 家; 净门店增长几乎停滞 (+78)",
            COLOR_RED)

add_callout(doc, "THESIS 3",
            "Forward PE 17.0x vs 同业 14.7x: 估值溢价 15.6%, 在 ±25% HOLD 区间; 上行需海外兑现, 下行风险是现金消耗",
            COLOR_RED)

add_callout(doc, "THESIS 4",
            "三档目标价: Bear $7.26 / Base $9.70 / Bull $12.14; 概率 30/50/20 加权期望 = US$9.55 (-14.7% 隐含)",
            COLOR_RED)

doc.add_paragraph()

# Different perspective (错位视角)
add_heading(doc, "二、错位视角: 我们 vs 市场 (Counter-Positioning)", level=2)

perspectives = [
    ("股价从 $41 跌到 $11 (-75%) 是机会",
     "跌 75% 是因为 FY25 净利腰斩, 当前 Forward PE 17x 仍在历史中位; 2024 30x+ 是 IPO 故事溢价, 不应回归"),
    ("加盟萎缩是行业问题, 蜜雪/古茗也有",
     "行业闭店率 5-10% (蜜雪 4.5%), 霸王从招股书 0.5-1.5% 跳到 Q1 26 ~3.4%, **变化幅度异常**; 加盟萎缩是公司问题"),
    ("转自营 = 收入并表, 长期利好",
     "自营 Opex +217%, G&A +31%, 净利率从 20% 跌到 12.6%; 蜜雪 2024 自营占比仅 2.5%, 管理层说\"不会做自营\""),
    ("公司有 ¥7.6B 现金, 烧得起",
     "Q1 26 单季烧 ¥746M, 折年化 ¥3B = FY25 净利的 2.5x; 7.6B 现金 ÷ 3B/年 = 2.5 年烧完")
]

p1 = doc.add_table(rows=1 + len(perspectives), cols=2)
p1.alignment = WD_TABLE_ALIGNMENT.CENTER
hdrs = ["市场观点", "我们观点 (带证据)"]
# header
for i, h in enumerate(hdrs):
    cell = p1.rows[0].cells[i]
    cell.text = ""
    para = cell.paragraphs[0]
    para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = para.add_run(h)
    set_font(run, size=10.5, bold=True, color=RGBColor(0xFF, 0xFF, 0xFF))
    tcPr = cell._tc.get_or_add_tcPr()
    shd = etree.SubElement(tcPr, qn('w:shd'))
    shd.set(qn('w:fill'), 'D90429' if i == 0 else '2B2D42')
for r_idx, (mkt, us) in enumerate(perspectives):
    for c_idx, val in enumerate([mkt, us]):
        cell = p1.rows[r_idx + 1].cells[c_idx]
        cell.text = ""
        para = cell.paragraphs[0]
        run = para.add_run(val)
        set_font(run, size=9.5,
                 bold=(c_idx == 1),
                 color=COLOR_BLACK if c_idx == 0 else COLOR_RED)
        if r_idx % 2 == 1:
            tcPr = cell._tc.get_or_add_tcPr()
            shd = etree.SubElement(tcPr, qn('w:shd'))
            shd.set(qn('w:fill'), 'F7F8FA')

doc.add_paragraph()
doc.add_page_break()

# === Page 3: Company Profile ===
add_heading(doc, "三、公司画像 (Company Profile)", level=1)
add_horizontal_line(doc)

profile_data = [
    ("公司全称", "Chagee Holdings Ltd. (茶姬控股有限公司)"),
    ("股票代码", "NASDAQ: CHA"),
    ("上市日期 / 发行价", "2025-04-17 / US$28.00 / ADS"),
    ("当前价 (2026-07-31)", "US$11.19 (东财)"),
    ("总股本 / 流通股本", "1.908 亿 ADS / 1.255 亿 ADS"),
    ("总市值", "US$21.35 亿 ≈ ¥144.3 亿"),
    ("52 周区间", "US$10.15 (2026-02-12) ~ US$41.80 (上市首日峰值)"),
    ("注册地", "开曼群岛 (运营总部: 四川成都)"),
    ("创始人 / CEO", "张俊杰 (Junjie Zhang, 2017 年创立)"),
    ("主营业务", "现制茶饮 (主推\"原叶鲜奶茶\")"),
    ("市场分布", "中国大陆 (主) + 马来西亚 / 新加坡 / 美国 (海外 138 家)"),
    ("主要股东", "张俊杰 (Partea Ltd, BVI 信托) ≈ 38.7%; XVC ≈ 20.3%; 琮碧秋实 ≈ 10.6%"),
    ("现金 (Q1 26)", "¥7.15B (US$1,036M, 含受限 + 定存)"),
    ("门店 (Q1 26)", "7,531 家 (加盟 6,741 + 自营 790)"),
    ("数据源", "SEC 20-F FY2025 / 6-K Q1 2026 / 东方财富"),
]
add_data_table(doc, ["项目", "内容"], profile_data, col_widths=[4.5, 12])

# Business model transformation
add_heading(doc, "3.1 模型转型: 加盟 → 自营 (双刃剑)", level=2)
add_paragraph(doc,
    "2017-2024: 97% 加盟, 轻资产快速扩张, 净利率 20%+;"
    "2025-2026: 加盟萎缩 + 自营激增 (+313% YoY),"
    "公司战略从\"卖原料 + 收权利金\"转向\"卖奶茶\"。",
    size=10, color=COLOR_BLACK)

transformation_rows = [
    ("门店总数", "6,681", "7,038", "7,338", "7,453", "7,531"),
    ("— 加盟", "6,490", "6,799", "6,971", "**6,838 ↓**", "**6,741 ↓↓**"),
    ("— 自营", "191", "239", "367", "615", "**790 (+313%)**"),
    ("— 大陆", "6,362", "6,666", "6,836", "6,700", "6,603"),
    ("— 海外", "128", "133", "135", "138", "138"),
]
add_data_table(doc, ["指标", "Q1 25", "Q2 25", "Q3 25", "Q4 25", "Q1 26"], transformation_rows, col_widths=[3.5, 2.5, 2.5, 2.5, 2.5, 2.5])

add_paragraph(doc, "🚨 关键发现: Q4 25 + Q1 26 连续 2 季度加盟关店 (合计 -230 家), 同期自营 +423 家;"
              "总门店仅 +78, 增长几乎停滞, 不是优化是替换。", size=10, color=COLOR_RED, bold=True)

doc.add_page_break()

# === Page 4: Industry & Financials ===
add_heading(doc, "四、行业空间 (Industry Landscape)", level=1)
add_horizontal_line(doc)

add_paragraph(doc, "中国现制茶饮市场 ≈ 66 万家门店 (2023, 灼识咨询);"
              "前 5 大企业市占率 35% (按 GMV) / 54.9% (按出杯量),"
              "格局已从分散走向头部集中。",
              size=10, color=COLOR_BLACK)

# TAM / SAM / SOM
add_heading(doc, "4.1 市场规模 (TAM / SAM / SOM)", level=2)
tam_rows = [
    ("TAM (总市场)", "现制饮品 (茶+咖+其他)", "2024 ≈ ¥3,000 亿 (终端零售)"),
    ("SAM (可服务)", "现制茶饮", "2024 ≈ ¥2,000 亿 (终端零售)"),
    ("SOM (公司可达)", "新茶饮 6 家头部", "2024 GMV 合计 ≈ ¥1,500 亿 (终端零售)"),
    ("CHA 2024 GMV", "霸王茶姬", "¥295 亿 (招股书披露)"),
    ("CHA 市占率 (GMV)", "霸王茶姬", "≈ 19.7% (基于 2024 GMV / 1,500 亿)"),
]
add_data_table(doc, ["层级", "范围", "数据 (2024)"], tam_rows, col_widths=[4, 4, 9])

# Peer comparison
add_heading(doc, "4.2 同业头部对比 (2025 全年)", level=2)
peer_rows = [
    ("蜜雪冰城", "2097.HK", "33.56", "5.88", "17.5%", "59,823", "下沉"),
    ("古茗", "1364.HK", "12.91", "3.11", "24.1%", "13,554", "南方+咖啡"),
    ("**CHAGEE**", "**CHA**", "**12.91**", "**1.17**", "**9.1%**", "**7,531**", "**高端**"),
    ("茶百道", "2555.HK", "5.40", "0.80", "15.2%", "8,621", "中部"),
    ("奈雪", "2150.HK", "4.33", "-0.24", "-5.6%", "1,646", "直营"),
]
add_data_table(doc, ["公司", "代码", "营收 (¥B)", "净利 (¥B)", "净利率", "门店", "定位"], peer_rows,
               col_widths=[2.5, 2, 2.5, 2.5, 2, 2, 3])

add_paragraph(doc, "数据源: 各公司 2025 年报 (2026 年 3 月披露); CHAGEE 来自 SEC 20-F + 6-K Q1 2026",
              size=8, color=COLOR_GRAY, space_after=8)

doc.add_page_break()

# === Page 5: Financials ===
add_heading(doc, "五、财务分析 (Financials)", level=1)
add_horizontal_line(doc)

# Three-year P&L
add_heading(doc, "5.1 损益表 — 三年趋势 (CNY 千元)", level=2)
pl_rows = [
    ("**营业收入**", "4,640,171", "12,405,582", "12,907,407", "+167%", "+4%"),
    ("**营业利润**", "1,074,103", "2,886,599", "1,347,237", "+169%", "**-53%**"),
    ("营业利润率", "23.1%", "23.3%", "10.4%", "+0.2pp", "**-12.9pp**"),
    ("**净利润**", "800,903", "2,516,114", "1,171,149", "+214%", "**-53%**"),
    ("**净利率**", "17.3%", "20.3%", "9.1%", "+3.0pp", "**-11.2pp**"),
]
add_data_table(doc, ["指标", "FY2023", "FY2024", "FY2025", "YoY 24", "YoY 25"], pl_rows, col_widths=[3, 2.5, 2.5, 2.5, 2, 2])

add_paragraph(doc, "🚨 营收断崖: 167% (2024) → 4% (2025); 净利润腰斩; 营业利润率从 23.3% 砍到 10.4%",
              size=10, color=COLOR_RED, bold=True)

# Q1 2026 cost structure
add_heading(doc, "5.2 Q1 2026 成本结构 (3 大红旗)", level=2)
cost_rows = [
    ("**自营店运营**", "157.0", "497.2", "**+217%**", "4.6% → 14.0%"),
    ("**管理费用**", "352.8", "462.0", "**+31%**", "10.4% → 13.0%"),
    ("**销售营销**", "299.3", "306.2", "+2.3%", "8.8% → 8.6%"),
    ("**原材料/仓储/物流**", "1,590.3", "1,574.5", "-1.0%", "46.9% → 44.4% ✅"),
    ("**加盟营收**", "3,149.9", "2,743.9", "**-12.9%**", "92.8% → 77.4%"),
    ("**自营营收**", "242.8", "802.1", "**+230%**", "7.2% → 22.6%"),
]
add_data_table(doc, ["项目", "Q1 25 (¥M)", "Q1 26 (¥M)", "YoY", "占营收%"], cost_rows, col_widths=[4, 3, 3, 2.5, 4])

add_paragraph(doc,
    "🚨 红旗: 1) 自营 Opex +217% (吞噬利润); 2) G&A +31% (运营效率下降);"
    "3) 加盟营收 -12.9% (萎缩), 自营 +230% (替换), 但合并后利润率压缩。",
    size=10, color=COLOR_RED, bold=True)

# Balance sheet
add_heading(doc, "5.3 资产负债表 (Q1 2026 关键变化)", level=2)
bs_rows = [
    ("**现金及等价物 (含受限+定存)**", "4,755", "7,892", "**-746 (Q1)**"),
    ("**总资产**", "6,596", "11,463", "+74%"),
    ("**股东权益**", "2,654", "7,342", "+177% (IPO 募资)"),
]
add_data_table(doc, ["指标 (¥M)", "2024-12-31", "2025-12-31", "变化"], bs_rows, col_widths=[6, 4, 4, 4])

add_paragraph(doc, "🚨 现金消耗警示: 2025 末 ¥7.89B → Q1 26 末 ¥7.15B, 单季烧 ¥746M;"
              "折年化 ¥3B, 是 FY25 净利的 2.5x。",
              size=10, color=COLOR_RED, bold=True)

doc.add_page_break()

# === Page 6: Valuation Methodology ===
add_heading(doc, "六、估值方法论 (Valuation Methodology)", level=1)
add_horizontal_line(doc)

add_heading(doc, "6.1 PE (Price-to-Earnings)", level=2)
add_paragraph(doc, "定义: 当前市值 / 过去 12 个月 (TTM) 归属股东净利润。"
              "反映市场对**已实现**盈利的定价。", size=10)
add_paragraph(doc, "公式: TTM PE = Market Cap / Net Income (过去 4 季度)", size=10, color=COLOR_GRAY)
add_paragraph(doc, "局限: 单一静态数字, 不反映成长性; 受一次性损益干扰。", size=10, color=COLOR_GRAY)

add_heading(doc, "6.2 Forward PE (NTM P/E)", level=2)
add_paragraph(doc, "定义: 当前市值 / 未来 12 个月 (NTM) 预期净利润。"
              "反映市场对**未来盈利**的定价, 嵌入成长预期。", size=10)
add_paragraph(doc, "公式: Forward PE = Market Cap / NTM EPS Estimate", size=10, color=COLOR_GRAY)
add_paragraph(doc, "关键变量: NTM 净利润 = 分析师一致预期 (consensus) 或 自建模型预测;"
              "本报告用 FY2026E 净利 (基于 Q1 2026 -34% YoY 趋势外推)。", size=10, color=COLOR_GRAY)

add_heading(doc, "6.3 横向 Peer Comparables (同业可比)", level=2)
add_paragraph(doc, "核心思想: 同行业的公司应享有**相近**的估值倍数; 差异需由成长性 / 利润率 / 风险解释。", size=10)
add_paragraph(doc, "步骤: 1) 选定可比公司 → 2) 收集 TTM/Forward PE → 3) 计算 median →"
              "4) 比较目标公司 → 5) 调整 (PEG / 利润率 / 规模差异)。", size=10)

add_heading(doc, "6.4 评级框架 (Rating Bands)", level=2)

add_data_table(doc,
    ["评级", "条件", "隐含回报"],
    [
        ("**BUY**", "Forward PE < Peer median × 0.75", "> +20%"),
        ("**HOLD**", "Forward PE ∈ [0.75, 1.25] × Peer median", "-10% ~ +10%"),
        ("**REDUCE / SELL**", "Forward PE > Peer median × 1.25", "< -20%"),
    ], col_widths=[4, 8, 5])

add_heading(doc, "6.5 目标价 (三档情景)", level=2)
add_paragraph(doc, "Base case: Target = FY2026E EPS × Industry Forward PE median", size=10)
add_paragraph(doc, "Bull case: Target = FY2026E EPS × (Industry median × 1.25)", size=10)
add_paragraph(doc, "Bear case: Target = FY2026E EPS × (Industry median × 0.75)", size=10)
add_paragraph(doc, "Prob-weighted: E(Target) = 30%×Bear + 50%×Base + 20%×Bull", size=10, color=COLOR_RED, bold=True)

doc.add_page_break()

# === Page 7: Peer Comparables ===
add_heading(doc, "七、横向 Peer Comparables (同业可比估值)", level=1)
add_horizontal_line(doc)

# Peer market cap
add_heading(doc, "7.1 Peer 市值 (CNY 统一口径, 2026-07-31)", level=2)
add_paragraph(doc, "汇率: 1 USD = 6.7575 CNY; 1 HKD = 0.9161 CNY (东方财富 2026-07-31)", size=8, color=COLOR_GRAY)

mkt_rows = [
    ("蜜雪冰城", "2097.HK", "HK$205.80", "HK$823 亿", "**¥75.4 B**"),
    ("古茗", "1364.HK", "HK$26.20", "HK$600 亿", "**¥55.0 B**"),
    ("**CHAGEE**", "**CHA**", "**US$11.19**", "**US$21.35 亿**", "**¥14.43 B**"),
    ("茶百道", "2555.HK", "HK$8.93", "HK$125 亿", "**¥11.5 B**"),
    ("奈雪", "2150.HK", "HK$2.20 (估)", "HK$35 亿", "¥3.2 B"),
]
add_data_table(doc, ["公司", "代码", "现价", "市值 (本地)", "市值 (¥B)"], mkt_rows, col_widths=[3, 2.5, 3, 4, 4])

# TTM PE
add_heading(doc, "7.2 TTM PE (基于 2025 净利)", level=2)
ttm_rows = [
    ("蜜雪冰城", "5.88", "75.4", "**12.8x**"),
    ("茶百道", "0.80", "11.5", "**14.4x**"),
    ("古茗", "3.11", "55.0", "**17.7x**"),
    ("奈雪", "-0.24", "3.2", "n.m. (亏损)"),
    ("**同业 median (剔除奈雪)**", "—", "—", "**14.4x**"),
    ("**CHAGEE**", "**1.17**", "**14.43**", "**12.3x ✓**"),
]
add_data_table(doc, ["公司", "净利 (¥B)", "市值 (¥B)", "TTM PE"], ttm_rows, col_widths=[5, 4, 4, 4])

add_paragraph(doc, "CHAGEE TTM PE 12.3x 较同业 median 14.4x **低 14.6%** — 静态视角偏低估",
              size=10, color=COLOR_GREEN, bold=True)

# Forward PE
add_heading(doc, "7.3 Forward PE (基于 FY2026E 净利)", level=2)
add_paragraph(doc, "同业 2026E 净利来源: 蜜雪 (东吴 51.2 亿); 茶百道 (国泰海通 7.88 亿); 古茗 (富瑞 31.4 亿)",
              size=8, color=COLOR_GRAY)

fwd_rows = [
    ("蜜雪冰城", "5.12", "75.4", "**14.7x**"),
    ("茶百道", "0.788", "11.5", "**14.6x**"),
    ("古茗", "3.14", "55.0", "**17.5x**"),
    ("奈雪", "0 (估)", "3.2", "n.m."),
    ("**同业 median (剔除奈雪)**", "—", "—", "**14.7x**"),
    ("**CHAGEE (自建)**", "**0.85**", "**14.43**", "**17.0x**"),
]
add_data_table(doc, ["公司", "26E 净利 (¥B)", "市值 (¥B)", "Forward PE"], fwd_rows, col_widths=[5, 4, 4, 4])

add_paragraph(doc, "CHAGEE Forward PE 17.0x 较同业 median 14.7x **高 15.6%** — 动态视角偏贵",
              size=10, color=COLOR_RED, bold=True)

# CHAGEE FY2026E estimation
add_heading(doc, "7.4 CHAGEE FY2026E 净利预测 (自建)", level=2)
fcst_rows = [
    ("**Bear**", "-40%", "全年趋势恶化, 自营 Opex 失控", "**0.65**"),
    ("**Base**", "**-28%**", "**Q1 落地, Q2-Q4 持平**", "**0.85**"),
    ("Bull", "-10%", "加盟企稳, 自营单店改善, 海外规模", "1.05"),
]
add_data_table(doc, ["情景", "Q1 26 YoY", "假设", "FY2026E 净利 (¥B)"], fcst_rows, col_widths=[2, 3, 8, 4])

add_paragraph(doc, "Base 论据: Q1 26 已显示加盟萎缩; 自营 Opex +217% 短期难改善; 海外 5.4% 不足以对冲; 一次性股权激励持续",
              size=9, color=COLOR_GRAY)

doc.add_page_break()

# === Page 8: Target Price & Rating ===
add_heading(doc, "八、目标价与评级 (Target Price & Rating)", level=1)
add_horizontal_line(doc)

# Forward PE rating
add_heading(doc, "8.1 Forward PE 评级结论", level=2)
rating_rows = [
    ("**CHAGEE Forward PE**", "**17.0x**", "**+15.6%**", "**HOLD** ✓"),
    ("CHAGEE TTM PE", "12.3x", "-14.6%", "BUY (T 视角)"),
]
add_data_table(doc, ["指标", "值", "vs 行业 median (14.7x)", "评级"], rating_rows, col_widths=[5, 3, 5, 4])

add_paragraph(doc, "🚨 冲突解读: TTM 偏低, Forward 偏高 → **转型期估值撕裂**;"
              "TTM (2025 净利 ¥1.17B) 是 IPO 当年高位, Forward (2026E ¥0.85B) 反映加盟萎缩 + 自营成本压力;"
              "市场用 Forward 看, 因此偏贵。",
              size=10, color=COLOR_RED, bold=True)

# Target price
add_heading(doc, "8.2 目标价 (三档情景)", level=2)
add_paragraph(doc, "EPS 基数: 2026E 净利 US$126M / 1.908 亿 ADS = **US$0.660 / ADS**", size=10)

tp_rows = [
    ("**Bear**", "**11.0x**", "0.660", "**$7.26**", "30%", "0.3"),
    ("**Base**", "**14.7x**", "0.660", "**$9.70**", "50%", "0.5"),
    ("**Bull**", "**18.4x**", "0.660", "**$12.14**", "20%", "0.2"),
    ("**期望值 (Prob-weighted)**", "—", "—", "**$9.55**", "100%", "1.0"),
]
add_data_table(doc, ["情景", "Forward PE", "EPS (US$)", "目标价 (US$)", "概率", "权重"],
               tp_rows, col_widths=[3, 3, 3, 3, 2, 2])

add_paragraph(doc, "评级: **HOLD** | 当前 $11.19 vs 期望 $9.55 = 隐含 **-14.7%**;"
              "在 ±25% HOLD 区间内, 不触发 SELL; 上行空间有限, 需催化。",
              size=10, color=COLOR_RED, bold=True)

# Rating thresholds
add_heading(doc, "8.3 评级阈值表 (Rule-Based)", level=2)
thresh_rows = [
    ("BUY", "Forward PE < 11.0x (行业中位 × 0.75)", "隐含 $7.26 / 股"),
    ("**HOLD** ✓", "**Forward PE ∈ [11.0, 18.4]**", "**当前 17.0x**"),
    ("REDUCE", "Forward PE > 18.4x (行业中位 × 1.25)", "隐含 $12.14 / 股"),
]
add_data_table(doc, ["评级", "触发条件", "注"], thresh_rows, col_widths=[3, 8, 5])

doc.add_page_break()

# === Page 9: SWOT ===
add_heading(doc, "九、SWOT 四象限", level=1)
add_horizontal_line(doc)

swot_rows = [
    ("**S 优势**", "1) 品牌力强 (高端茶饮心智);\n2) 单店 GMV ¥356K (Q1 26) 高于行业;\n3) 海外布局早 (138 家店);\n4) IPO 后现金 ¥7.6B;\n5) 茶园供应链整合 (鲁继胜合作)"),
    ("**W 劣势**", "1) 净利率 9.1% (2025) **低于同业** (蜜雪 17.5% / 古茗 24.1%);\n2) 加盟萎缩信号;\n3) 自营成本失控 (+217%);\n4) G&A 13% 营收占比偏高;\n5) 客户集中度高"),
    ("**O 机会**", "1) 海外市场空白 (北美 / 东南亚);\n2) 现制茶饮市场规模年增 15%+;\n3) 咖啡品类延伸 (古茗示范);\n4) 美股二次融资能力"),
    ("**T 威胁**", "1) 蜜雪冰城下沉碾压 (6 万店 vs 7.5 千店);\n2) 古茗 / 喜茶高端反扑;\n3) 外卖平台补贴退潮;\n4) 食品安全黑天鹅 (2026/1 徒手制作事件);\n5) 港股新茶饮估值整体回调"),
]
add_data_table(doc, ["类别", "详情"], swot_rows, col_widths=[2.5, 14])

doc.add_page_break()

# === Page 10: Red Team (蓝军) ===
add_heading(doc, "十、蓝军自攻击 (Red Team) — 反方观点", level=1)
add_horizontal_line(doc)

add_callout(doc, "蓝军 #1", "加盟萎缩是公司主动调整, 不是品牌失败 — 部分成立, 但总门店仅 +78 难以解释为优化",
            COLOR_AMBER)
add_paragraph(doc,
    "正方论据: 蜜雪 2025 海外关 428 家, 行业都在优化;"
    "反方论据: 蜜雪净增 13,344 家, 是结构优化; 霸王总门店仅 +78 (Q1 26), 加盟 -230 + 自营 +308, 不是优化是替换。",
    size=9, color=COLOR_GRAY, indent=0.3)

add_callout(doc, "蓝军 #2", "2024 净利率 20.3% 是真实水平, 2025 是一次性回归 — 不成立, 单店盈利能力腰斩",
            COLOR_AMBER)
add_paragraph(doc,
    "正方论据: 2024 是 IPO 故事年份, 加盟商进货 + 推新品冲业绩;"
    "反方论据: 2024 单店年净利 ¥391K, 2025 ¥157K — 单店盈利能力**腰斩**, 不可解释为一次性。",
    size=9, color=COLOR_GRAY, indent=0.3)

add_callout(doc, "蓝军 #3", "CHAGEE 是中国星巴克, 海外值得给溢价 — 不成立, 5% 占比远未到给溢价阶段",
            COLOR_AMBER)
add_paragraph(doc,
    "正方论据: 首店北美 (洛杉矶) 2025 落地, 海外 GMV +139% YoY;"
    "反方论据: 138 家海外门店 0 盈利数据; 星巴克海外 20+ 年才规模化, CHAGEE 海外 5% 营收, 远未到给溢价阶段。"
    "海外是 long-dated call option, 不应 price-in 当前估值。",
    size=9, color=COLOR_GRAY, indent=0.3)

add_callout(doc, "蓝军 #4", "自营转型 = 收入并表, 是看多逻辑 — 部分成立, 但收入并表 ≠ 利润并表",
            COLOR_AMBER)
add_paragraph(doc,
    "正方论据: 自营收入从 ¥243M (Q1 25) 暴涨到 ¥802M (Q1 26), 占比 7.2% → 22.6%;"
    "反方论据: 自营 Opex +217%, G&A +31%, 整体净利率从 20% → 12.6%; 公司不披露自营净利, 转型期承压。",
    size=9, color=COLOR_GRAY, indent=0.3)

doc.add_page_break()

# === Page 11: Risks & Monitoring KPI ===
add_heading(doc, "十一、风险 (Risks)", level=1)
add_horizontal_line(doc)

risks = [
    ("加盟商持续撤离", "如果 Q2-Q4 2026 加盟单季净关 > 200 家, 转型故事破灭, 估值需重估"),
    ("现金消耗失控", "如年化烧钱 > ¥4B, 2 年内需再融资, 股权稀释风险"),
    ("海外扩张失败", "北美 / 东南亚单店模型不盈利, 海外故事破灭, 失去 30x+ 故事溢价"),
    ("外卖平台补贴战重启", "蜜雪 2025 H2 实证影响; 若平台重新补贴, 单店 GMV 进一步压缩"),
    ("食品安全黑天鹅", "2026/1 徒手制作事件已触发股价单日 -15%; 类似事件可再发"),
    ("可比公司估值整体下移", "蜜雪 2025/7 跌 66%, 古茗 2025/3 跌 8%; 行业 β 风险"),
    ("汇率风险", "USD 报告口径, CNY 收入, 人民币贬值时 USD EPS 受益"),
    ("管理层 / 股权风险", "BVI 信托结构 + 关联交易 (Partea / 鲁继胜), 透明度争议"),
]
add_data_table(doc, ["风险项", "影响"], risks, col_widths=[5, 12])

# Monitoring KPI
add_heading(doc, "十二、监控 KPI (Monitoring Thresholds)", level=1)
add_horizontal_line(doc)

kpi_rows = [
    ("月度新增加盟门店", "-32 (Q1 26 平均)", "< -67", "< -133", "黄灯: 关注续约率; 红灯: 立即下修估值"),
    ("大陆月均单店 GMV", "¥356,080", "< ¥330,000", "< ¥300,000", "黄灯: 同店增长转负; 红灯: 单店模型恶化"),
    ("海外门店数 (年净增)", "+10 (1 年)", "< +20", "< 0", "黄灯: 海外扩张迟缓; 红灯: 海外故事破灭"),
    ("自营 Opex / 营收", "14.0%", "> 16%", "> 18%", "黄灯: 自营亏损扩大; 红灯: 转型失败"),
    ("现金消耗 (折年化)", "¥3.0B", "> 净利润 1.5x", "> 净利润 2x", "黄灯: 现金流压力; 红灯: 需再融资"),
    ("加盟商闭店率 (年化)", "~3.4% (Q1 26 估算)", "> 5%", "> 8%", "黄灯: 加盟信心动摇; 红灯: 商业模式质疑"),
    ("Non-GAAP 净利率", "14.3% (Q1 26)", "< 12%", "< 10%", "黄灯: 利润持续压缩; 红灯: 估值需重估"),
]
add_data_table(doc, ["KPI", "当前值 (Q1 2026)", "黄灯", "红灯", "触发动作"], kpi_rows, col_widths=[3, 3, 2.5, 2.5, 5])

doc.add_page_break()

# === Page 12: Conclusion & Disclaimers ===
add_heading(doc, "十三、结论 (Conclusion)", level=1)
add_horizontal_line(doc)

add_paragraph(doc, "**首次覆盖 — HOLD (中性), 目标价 US$9.55**", size=14, bold=True, color=COLOR_RED, space_after=8)

add_paragraph(doc, "估值方法: PE + Forward PE + 横向 Peer Comparables", size=10, color=COLOR_GRAY)
add_paragraph(doc, "数据截止: 2026-07-31 收盘", size=10, color=COLOR_GRAY)
add_paragraph(doc, "评级矩阵:", size=10, color=COLOR_GRAY)
doc.add_paragraph()

# Final rating box
p = doc.add_paragraph()
p.alignment = WD_ALIGN_PARAGRAPH.LEFT
p.paragraph_format.space_before = Pt(6)
p.paragraph_format.space_after = Pt(6)
pPr = p._p.get_or_add_pPr()
shd = etree.SubElement(pPr, qn('w:shd'))
shd.set(qn('w:fill'), 'EDF2F7')

r = p.add_run("  评级  ")
set_font(r, size=14, bold=True, color=RGBColor(0xFF, 0xFF, 0xFF))
rPr = r._r.get_or_add_rPr()
shd2 = etree.SubElement(rPr, qn('w:shd'))
shd2.set(qn('w:fill'), 'D90429')

r = p.add_run("  HOLD (中性)   |   ")
set_font(r, size=14, bold=True, color=COLOR_BLACK)

r = p.add_run("目标价 US$9.55   |   ")
set_font(r, size=12, color=COLOR_BLACK)

r = p.add_run("现价 US$11.19   |   ")
set_font(r, size=12, color=COLOR_BLACK)

r = p.add_run("隐含 -14.7%")
set_font(r, size=14, bold=True, color=COLOR_RED)

doc.add_paragraph()

# Final summary
add_paragraph(doc, "📌 核心结论", size=12, bold=True, color=COLOR_RED, space_after=4)

bullets = [
    "Forward PE 17.0x 较同业 median 14.7x 溢价 15.6%, 落在 HOLD 区间 (0.75-1.25 × median)",
    "TTM PE 12.3x vs 同业 14.4x 低 14.6% — 静态视角低估, 但市场用 Forward 定价",
    "三档目标价: Bear $7.26 / Base $9.70 / Bull $12.14, 概率加权期望 $9.55",
    "上行催化: 海外兑现 + 自营单店改善 + Q3/Q4 GMV 企稳",
    "下行风险: 加盟崩塌 + 现金耗尽 + 食品安全事件 + 行业 β",
    "监控 KPI 7 项, 阈值已给; 触发红灯需立即下修估值",
]
for b in bullets:
    add_bullet(doc, b, indent=0.3)

doc.add_paragraph()
add_horizontal_line(doc, color="2B2D42", size=6)

# Source references
add_heading(doc, "十四、数据源 (Source References)", level=2)
sources = [
    "CHAGEE 损益表 — SEC EDGAR XBRL API (data.sec.gov)",
    "CHAGEE 20-F FY2025 — SEC accession 0001104659-26-050766 (2026-04-29)",
    "CHAGEE Q1 2026 — SEC 6-K ex99-1 (2026-05-29, accession 0001104659-26-067770)",
    "CHAGEE 当前价 — 东方财富 quote.eastmoney.com (2026-07-31 收盘)",
    "蜜雪 2025 财报 — 经济导报 / 蜜雪 2097.HK 公告 (2026-03-24)",
    "古茗 2025 财报 — 观点网 / 古茗 1364.HK 公告 (2026-03-25)",
    "茶百道 2025 财报 — 茶百道 2555.HK 公告 (2026-03-27)",
    "奈雪 2025 财报 — 观点网 / 奈雪 2150.HK 公告 (2026-03-26)",
    "茶百道 26E 预测 — 国泰海通证券 (2025-04-06)",
    "古茗 26E 预测 — 富瑞 Jefferies (2026-07-10)",
    "蜜雪 26E 预测 — 东吴证券 (2025-04-23)",
    "汇率 — 东方财富 (2026-07-31)",
]
for s in sources:
    add_bullet(doc, s, indent=0.3, color=COLOR_GRAY, size=8.5)

# Disclaimer
add_heading(doc, "免责声明 (Disclaimer)", level=2)
add_paragraph(doc,
    "本报告由守仁资产研究 (Shouren Research) 基于公开信息整理,"
    "包括 SEC EDGAR XBRL API, 各公司公开财报, 公开新闻报道等。"
    "本报告不构成投资建议, 投资者应独立判断并承担风险。"
    "报告中所有数据截至 2026-08-08, 股价截至 2026-07-31 收盘。"
    "分析师对报告内容的真实性, 准确性, 完整性力求审慎, 但不承担任何责任。",
    size=8, color=COLOR_GRAY, space_after=4)

# Save
output_path = "/Users/mac/.minimax-agent-cn/projects/value-investing-agent/projects/cha-initiation-2026/05-writer/report.docx"
doc.save(output_path)
print(f"✅ Report saved: {output_path}")
print(f"   Size: {len(open(output_path, 'rb').read())} bytes")
